//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tienda.App_LocalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca añadida correctamente.
        /// </summary>
        public static string añadidaMarcaMsg {
            get {
                return ResourceManager.GetString("añadidaMarcaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto añadido correctamente.
        /// </summary>
        public static string añadidoProducto {
            get {
                return ResourceManager.GetString("añadidoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de producto añadido correctamente.
        /// </summary>
        public static string añadidoTipoProductoMsg {
            get {
                return ResourceManager.GetString("añadidoTipoProductoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir.
        /// </summary>
        public static string añadirBtn {
            get {
                return ResourceManager.GetString("añadirBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir marca.
        /// </summary>
        public static string añadirMarcaHeader {
            get {
                return ResourceManager.GetString("añadirMarcaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir producto.
        /// </summary>
        public static string añadirProducto {
            get {
                return ResourceManager.GetString("añadirProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir tipo de producto.
        /// </summary>
        public static string añadirTipoProducto {
            get {
                return ResourceManager.GetString("añadirTipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string buscarText {
            get {
                return ResourceManager.GetString("buscarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string codigoLbl {
            get {
                return ResourceManager.GetString("codigoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string colorLbl {
            get {
                return ResourceManager.GetString("colorLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2021 Alejandro Collazo.
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string descripcionLbl {
            get {
                return ResourceManager.GetString("descripcionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al añadir la marca en la base de datos.
        /// </summary>
        public static string errorAñadirMarcaMsg {
            get {
                return ResourceManager.GetString("errorAñadirMarcaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al añadir el producto.
        /// </summary>
        public static string errorAñadirProducto {
            get {
                return ResourceManager.GetString("errorAñadirProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al añadir el tipo de producto en la base de datos.
        /// </summary>
        public static string errorAñadirTipoProductoMsg {
            get {
                return ResourceManager.GetString("errorAñadirTipoProductoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor numérico.
        /// </summary>
        public static string errorMsgNumber {
            get {
                return ResourceManager.GetString("errorMsgNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo es obligatorio.
        /// </summary>
        public static string errorMsgRequired {
            get {
                return ResourceManager.GetString("errorMsgRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string marcaLbl {
            get {
                return ResourceManager.GetString("marcaLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La marca ya existe.
        /// </summary>
        public static string marcaRepetidaMsg {
            get {
                return ResourceManager.GetString("marcaRepetidaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar productos.
        /// </summary>
        public static string menuInsertar {
            get {
                return ResourceManager.GetString("menuInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar productos.
        /// </summary>
        public static string menuListar {
            get {
                return ResourceManager.GetString("menuListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string nombreLbl {
            get {
                return ResourceManager.GetString("nombreLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string precioLbl {
            get {
                return ResourceManager.GetString("precioLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacar ticket.
        /// </summary>
        public static string sacarTicketBtn {
            get {
                return ResourceManager.GetString("sacarTicketBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string stockLbl {
            get {
                return ResourceManager.GetString("stockLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talla.
        /// </summary>
        public static string tallaLbl {
            get {
                return ResourceManager.GetString("tallaLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienda.
        /// </summary>
        public static string textIcon {
            get {
                return ResourceManager.GetString("textIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo producto.
        /// </summary>
        public static string tipoProductoLbl {
            get {
                return ResourceManager.GetString("tipoProductoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de producto ya existe.
        /// </summary>
        public static string tipoProductoRepetidoMsg {
            get {
                return ResourceManager.GetString("tipoProductoRepetidoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar productos.
        /// </summary>
        public static string tituloBuscar {
            get {
                return ResourceManager.GetString("tituloBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string tituloInicio {
            get {
                return ResourceManager.GetString("tituloInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar.
        /// </summary>
        public static string tituloInsertar {
            get {
                return ResourceManager.GetString("tituloInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado.
        /// </summary>
        public static string tituloListado {
            get {
                return ResourceManager.GetString("tituloListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de los productos.
        /// </summary>
        public static string tituloListadoProductos {
            get {
                return ResourceManager.GetString("tituloListadoProductos", resourceCulture);
            }
        }
    }
}
